controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    hand_joint_state_broadcaster:
      type: hand_joint_state_broadcaster/HandJointStateBroadcaster

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_joint_trajectory_controller:
      type: hand_joint_trajectory_controller/HandJointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    force_mode_controller:
      type: ur_controllers/ForceModeController

    freedrive_mode_controller:
      type: ur_controllers/FreedriveModeController

    passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController

    tcp_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    ur_configuration_controller:
      type: ur_controllers/URConfigurationController

speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "$(var tf_prefix)"

io_and_status_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

ur_configuration_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: $(var tf_prefix)tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: $(var tf_prefix)tool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)elbow_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_3_joint: { trajectory: 0.2, goal: 0.1 }


scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)elbow_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

passthrough_trajectory_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

forward_velocity_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint

force_mode_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

freedrive_mode_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

tcp_pose_broadcaster:
  ros__parameters:
    frame_id: $(var tf_prefix)base
    pose_name: $(var tf_prefix)tcp_pose
    tf:
      child_frame_id: $(var tf_prefix)tool0_controller

hand_joint_state_broadcaster:
  ros__parameters:
    joints:
      - forearm:1--base:1
      - palm_axis:1--forearm:1
      - palmL:1--palm_axis:1
      - thumb_adduction_motor
      - thumb_flexion_motor
      - index_flexion_motor
      - middle_flexion_motor
      - ring_small_flexion_motor
    hand_joints:
      - forearm:1--base:1
      - palm_axis:1--forearm:1
      - palmL:1--palm_axis:1
      - Thumb_axis--palmL:1
      - Index_Proximal--palmL:1
      - Index_Middle--Index_Proximal
      - Index_Distal--Index_Middle
      - Small_Proximal--palmL:1
      - Small_Middle--Small_Proximal
      - Small_Distal--Small_Middle
      - Ring_Proximal--palmL:1
      - Ring_Middle--Ring_Proximal
      - Ring_Distal--Ring_Middle
      - Thumb_Methacarpal--Thumb_axis
      - Thumb_Proximal--Thumb_Methacarpal
      - Thumb_Distal--Thumb_Proximal
      - Middle_Proximal--palmL:1
      - Middle_Middle--Middle_Proximal
      - Middle_Distal--Middle_Middle   

hand_joint_trajectory_controller:
  ros__parameters:
    joints:
    - forearm:1--base:1
    - palm_axis:1--forearm:1
    - palmL:1--palm_axis:1
    command_interfaces:
      - position
    state_interfaces:
      - position

joint_state_broadcaster:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    interfaces:
    - position
    - velocity